<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: yii.php 3133 2011-03-27 01:36:37Z qiang.xue $
 */
return array (
  '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" ist bereits vergeben.',
  '{attribute} "{value}" is invalid.' => '{attribute} "{value}" ist ungültig.',
  '{attribute} cannot accept more than {limit} files.' => '{attribute} akzeptiert nicht mehr als {limit} Dateien.',
  '{attribute} cannot be blank.' => '{attribute} ei tohi tühi olla.',
  '{attribute} is in the list.' => '{attribute} ist nicht in Liste enthalten.',
  '{attribute} is invalid.' => '{attribute} ist ungültig.',
  '{attribute} is not a valid URL.' => '{attribute} ist keine gültige URL.',
  '{attribute} is not a valid email address.' => '{attribute} vigane!',
  '{attribute} is not in the list.' => '{attribute} ist nicht in der Liste.',
  '{attribute} is of the wrong length (should be {length} characters).' => '{attribute} hat die falsche Länge (Es sollten {length} Zeichen sein).',
  '{attribute} is too big (maximum is {max}).' => '{attribute} ist zu groß (Maximum ist {max}).',
  '{attribute} is too long (maximum is {max} characters).' => '{attribute} ist zu lang (Maximal {max} Zeichen).',
  '{attribute} is too short (minimum is {min} characters).' => '{attribute} ist zu kurz (Mindestens {min} Zeichen).',
  '{attribute} is too small (minimum is {min}).' => '{attribute} ist zu klein (Minimum ist {min}).',
  '{attribute} must be a number.' => '{attribute} muss eine Zahl sein.',
  '{attribute} must be an integer.' => '{attribute} muss eine ganze Zahl sein.',
  '{attribute} must be either {true} or {false}.' => '{attribute} muss entweder {true} oder {false} sein.',
  '{attribute} must be greater than "{compareValue}".' => '{attribute} muss größer als "{compareValue}" sein.',
  '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} muss größer oder gleich "{compareValue}" sein.',
  '{attribute} must be less than "{compareValue}".' => '{attribute} muss kleiner als "{compareValue}" sein.',
  '{attribute} must be less than or equal to "{compareValue}".' => '{attribute} muss kleiner oder gleich "{compareValue}" sein.',
  '{attribute} must be repeated exactly.' => '{attribute} muss genau wiederholt werden.',
  '{attribute} must be {type}.' => '{attribute} muss {type} sein.',
  '{attribute} must be {value}.' => '{attribute} muss {value} sein.',
  '{attribute} must not be equal to "{compareValue}".' => '{attribute} darf nicht gleich "{compareValue}" sein.',
  'The verification code is incorrect.' => 'Kontrollkood on vigane!',
  'Get a new code' => 'Uus kontrollkood',
  'Letters are not case-sensitive.' => 'Tähed pole tõusutundlikud',
);
